algoritmo "operadores_relacionais"

var
   a, b, c: inteiro
   resultado: logico
inicio
// < menor que, > maior que, <= menor ou igual a, >= maior ou igual a, = igual a, <> diferente de

      a <- 10
      b <- 6
      c <- 4

      escreval(a<b)
      escreval(a>b)
      escreval(a<=b)
      escreval(a>=b)
      escreval(a=b)
      escreval(a<>b)
      
      escreval()
      
      resultado <- a<>b+c
      escreva(resultado)
fimalgoritmo
