algoritmo "limpa_tela"

var

inicio
      escreval("fnawluehfawiufilawuhfeilawhfiwahefiwhef")
      escreval("fnawluehfawiufilawuhfeilawhfiwahefiwhef")
      escreval("fnawluehfawiufilawuhfeilawhfiwahefiwhef")
      escreval("fnawluehfawiufilawuhfeilawhfiwahefiwhef")
      escreval("fnawluehfawiufilawuhfeilawhfiwahefiwhef")
      limpatela
      escreval("fnawluehfawiufilawuhfeilawhfiwahefiwhef")
fimalgoritmo
