algoritmo "operadores_aritméticos"

var
   a, b: inteiro
   resultado: real
inicio
// +, -, *, /, \, ^, %
// ao se utilizar 2 ou mais operadores, as regras matemáticas de ordem se aplicam, ou seja, primeiro o que está entre parenteses, depois o que está exponenciado, depois multiplicação e divisão e por último soma e subtração
      a <- 5
      b <- 7
      resultado <- (a+b) / 2
      escreva(resultado)
fimalgoritmo
